### ISSUE TITLE
Bad Gateway 502

### ISSUE THREAD

**Issue by AdamLee321** [mtalcott/google-photos-deduper#42]
I am getting a 502 Bad Gateway when running get started I noticed the same issue on two other endpoints in the console too. I have attached screenshots in case anyone knows the answer. Thanks in advance.

![Screenshot 2024-02-18 203350](https://github.com/mtalcott/google-photos-deduper/assets/22890658/6dc1c8d3-1070-4683-b049-9d77f4bdd99c)
![Screenshot 2024-02-18 2033501](https://github.com/mtalcott/google-photos-deduper/assets/22890658/873252df-ec5f-4b17-8621-5460dd1d8b10)

**Comment by 3choBoomer** [comment]
I experienced this on an older machine that could not handle running the multiple docker containers needed for this application.

I moved to a newer and faster machine and it worked fine.

**Comment by tomch3ng** [comment]
Are you using a Mac? I encountered this issue on my Mac, and it's because the server container defaults to port 5000, but that's in use by MacOS. You can confirm this by this error message in the console:
`Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use`
Docker Desktop or `docker ps` would also show two of the seven containers in "Created", but not "Running" state:
<img width="1440" alt="Screenshot 2024-05-27 at 5 01 05 PM" src="https://github.com/mtalcott/google-photos-deduper/assets/6641300/b789b33d-7327-4c86-9522-b314953b9bc8">

To fix this, simply change line 42 in `docker-compose.yml` to `      - "5001:5000" # flask` from `      - "5000:5000" # flask`.

**Comment by mtalcott** [comment]
I have merged @tomch3ng's port remapping fix, #48. @AdamLee321 @3choBoomer this should fix your issue, please confirm.
